### ISSUE TITLE
Actividad 5

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-edgarmauricio123#1]
Edgar Mauricio Sarmiento Ruiz
Grupo: 1BS
Cuadro comparativo de los diferentes tipos de texto.

![CUADRO-COMPARATIVO-TIPOS-DE-TEXTO](https://user-images.githubusercontent.com/112227375/191882362-85f9103a-b729-47d5-9fe9-7624b54c3a33.png)

**Comment by YaelTrinidad** [comment]
ACT 5 CUADRO COMPARATIVO
"CARACTERISTICAS Y ESTRUCTURAS DE LOS TEXTOS"
DEL 20% DE LA ACTIVIDAD, DADA LA RUBRICA OBTUVISTE EL 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
